---
- include: "{{ ansible_os_family }}.yml"

- name: owner
  user:
    name: "{{ sites[item]['owner'] }}"
    shell: /bin/bash
    groups: "{{ sites[item]['groups'] | default(omit) }}"
  with_items: "{{ sites }}"
  when: sites[item]['owner'] is defined

- name: owner authorized_key
  authorized_key:
    user: "{{ sites[item]['owner'] }}"
    state: present
    key: "{{ sites[item]['authorized_key'] }}"
  with_items: "{{ sites }}"
  when: sites[item]['owner'] is defined and sites[item]['authorized_key'] is defined

- name: Sites private key
  copy:
    content: "{{ sites_ssh['key'] }}"
    dest: /var/www/key
    mode: 0644

- name: Sites pub key
  copy:
    content: "{{ sites_ssh['pub_key'] }}"
    dest: /var/www/html/pub_key
    mode: 0644

- name: Checkout site # noqa 401
  git:
    repo: "{{ sites[item]['url'] }}"
    dest: "/var/www/html/{{ sites[item]['context'] }}"
    key_file: /var/www/key
  with_items: "{{ sites }}"
  when: sites[item]['url'] is defined
  notify: chown-site-owner

- name: Site directory
  file:
    path: "/var/www/html/{{ sites[item]['context'] }}"
    owner: "{{ sites[item]['owner'] | default(omit) }}"
    group: "{{ sites[item]['owner'] | default(omit) }}"
    state: directory
    mode: 0644
  with_items: "{{ sites }}"
  when: sites[item]['url'] is not defined
