---
- name: Add linux user
  user:
    name: sonarqube
    comment: SonarQube
    shell: /bin/bash

- name: Create root directory
  file:
    path: "{{ sonarqube_home }}"
    state: directory
    group: sonarqube
    owner: sonarqube
    mode: 0755

- name: Create install folder
  file:
    path: "{{ sonarqube_home_version }}"
    state: directory
    group: sonarqube
    owner: sonarqube
    mode: 0644
  register: install_symlink

- name: Check installed
  stat:
    path: "{{ sonarqube_home_version }}/conf"
  register: sonarqube_installed

- name: Download
  get_url:
    url: "{{ sonarqube_versions[sonarqube_version]['url'] }}"
    dest: "/tmp/{{ sonarqube_home_version|basename }}.zip"
    validate_certs: "{{ sonarqube_download_validate_certs }}"
    checksum: "{{ sonarqube_versions[sonarqube_version]['checksum'] }}"
  notify: restart sonarqube
  when: not sonarqube_installed.stat.exists

- name: Unzip package
  package:
    name: unzip
    state: present

- name: Unzip
  unarchive:
    src: "/tmp/{{ sonarqube_home_version|basename }}.zip"
    dest: "{{ sonarqube_home }}"
    copy: false
    group: sonarqube
    owner: sonarqube
  when: not sonarqube_installed.stat.exists
  notify:
    - lcm-version-file

- name: Create symbolic link install
  file:
   src: "{{ sonarqube_home_version }}"
   dest: "{{ sonarqube_home }}/sonarqube"
   state: link

- name: Create symbolic link jar
  file:
   src: "{{ sonarqube_home_version }}/lib/sonar-application-{{ sonarqube_version }}.jar"
   dest: "{{ sonarqube_home_version }}/lib/sonar-application.jar"
   state: link

- name: Copy data dir ( part of upgrade )
  command: "rsync -az --delete --recursive {{ sonarqube_home_version_current }}/extensions/plugins/ {{ sonarqube_home_version }}/extensions/plugins/"
  when: sonarqube_lcm['operation'] == 'upgrade'
