---
- name: Stop SonarQube for LCM
  service: name=sonarqube state=stopped
  when: sonarqube_lcm['operation'] in ['upgrade','rollback','rollforward']

- include: database.yml
- include: install.yml
- include: configuration.yml

- include: plugins.yml
  vars:
    sonarqube_plugins_jar_location: "{{ sonarqube_home_version }}/extensions/plugins"
# Community branch plugin installs also in lib common    
- include: plugins.yml
  vars:
    sonarqube_plugins_jar_location: "{{ sonarqube_home_version }}/lib/common"

- include: service.yml
- include: jmx.yml

- name: Allow Sonar time to build on first start.
  pause: seconds=180
  when: install_symlink.changed
  tags: ['skip_ansible_lint']

- name: Make sure Sonar is responding on the configured port.
  wait_for: port=9000 delay=3 timeout=300
