---
- name: Systemd service
  template:
    src: sonar.unit.j2
    dest: /etc/systemd/system/sonarqube.service
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr == 'systemd'"
  notify:
    - systemctl-daemon-reload
    - restart sonarqube

- name: Ensure Sonar is running and set to start on boot.
  service: name=sonarqube state=started enabled=yes
