---
- name: Create root directory
  file:
    path: "{{ desktop_home }}"
    state: directory
    mode: 0400

- name: Files
  include_role:
    name: c2platform.core.files
    tasks_from: main
  vars:
    common_files_role_name: desktop

- name: Docker
  include_role:
    name: c2platform.mw.docker
    tasks_from: main
    handlers_from: main
  vars:
    docker_role_name: desktop

- name: Write VNC password  # just for reference
  copy:
    content: "{{ item['vnc_password']|default(desktop_vnc_password) }}"
    dest: "{{ desktop_home }}/{{ item['name'] }}"
    mode: 0400
  with_items: "{{ desktop_docker_containers }}"
  loop_control:
    label: "{{ item['name'] }} → {{ desktop_home }}/{{ item['name'] }}"

- name: Set VNC password
  shell: >-
    docker exec {{ item['name'] }}
    /bin/bash -c  "/usr/local/bin/vncserver-vncpasswd $VNC_PASSWORD vagrant"
  with_items: "{{ desktop_docker_containers }}"
  environment:
    VNC_PASSWORD: "{{ item['vnc_password']|default(desktop_vnc_password) }}"
  loop_control:
    label: "{{ item['name'] }}"
