---
- block:
  - name: Create database
    include_role:
      name: c2platform.core.postgresql_tasks
      tasks_from: database
    vars:
      lcm_role_upgrade: guacamole
  delegate_to: "{{ guacamole_database_inventory_hostname }}"
  become_user: postgres

- name: Check initdb.sql
  stat:
    path: "{{ guacamole_home_version }}/initdb.sql"
  register: initdb_script_path

- name: Create initdb.sql
  command:
    cmd: "docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres"
  when: not initdb_script_path.stat.exists
  register: initdb_script

- name: Local copy initdb.sql
  copy:
    content: "{{ initdb_script.stdout }}"
    dest: "{{ guacamole_home_version }}/initdb.sql"
    mode: 0644
  when: not initdb_script_path.stat.exists

- name: Run initdb.sql
  postgresql_query:
    db: "{{ guacamole_database_name_version }}"
    login_host: "{{ guacamole_database_host }}"
    login_user: "{{ guacamole_database_username }}"
    login_password: "{{ guacamole_database_password }}"
    port: "{{ guacamole_database_port }}"
    path_to_script: "{{ guacamole_home_version }}/initdb.sql"
  when: not initdb_script_path.stat.exists

#- debug:
#    var: initdb_script.stdout

#postgresql_db

# > {{ guacamole_home_version }}/initdb.sql