---
- name: Docker compose pip package
  pip:
    name: docker-compose
    version: 1.9.0
    state: present

- name: Create docker network
  docker_network:
    name: guacamole

- name: Pull image
  docker_image:
    name: "{{ item.repo }}:{{ item.version }}"
    source: pull
  with_items:
    - repo: "{{ guacamole_daemon_repo }}"
      version: "{{ guacamole_version }}"
    - repo: "{{ guacamole_web_repo }}"
      version: "{{ guacamole_version }}"

- name: Run guacamole
  docker_container:
    name: "{{ guacamole_daemon_name }}"
    image: "{{ guacamole_daemon_repo }}:{{ guacamole_version }}"
    networks:
      - name: guacamole
    restart_policy: unless-stopped

- name: Run guacamole web
  docker_container:
    name: "{{ guacamole_web_name }}"
    image: "{{ guacamole_web_repo }}:{{ guacamole_version }}"
    networks:
      - name: guacamole
    etc_hosts: "{{ guacamole_container_extra_hosts|default(omit) }}"
    env: "{{ guacamole_web_settings }}"
    ports:
     - "{{ guacamole_web_port }}:8080"
    restart_policy: unless-stopped
