---
#- name: Stop for LCM
#  service: name=guacamole state=stopped
#  when: guacamole_lcm['operation'] in ['upgrade','rollback','rollforward']

- name: Add account
  user:
    name: "{{ guacamole_owner }}"
    comment: guacamole
    shell: /bin/bash

- name: Setup home dirs
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ guacamole_owner }}"
    owner: "{{ guacamole_owner }}"
    mode: 0644
  with_items:
    - "{{ guacamole_home }}"
    - "{{ guacamole_home_version }}"

- include: database.yml

- name: Files
  include_role:
    name: c2platform.core.files
    tasks_from: main
  vars:
    common_files_role_name: guacamole

- name: Docker
  include_role:
    name: c2platform.mw.docker
    tasks_from: main
    handlers_from: main
  vars:
    docker_role_name: guacamole
