- name: start service firewalld
  systemd:
    name: firewalld
    state: restarted

- name: permit traffic in default zone on port 8443/tcp
  firewalld:
    port: "{{ confluence_web_port_https }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes