---
- name: Home
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ confluence_home }}"

- include: download.yml
  when: confluence_lcm['operation'] in ['upgrade','install']

- name: stop for upgrade, rollback or rollfoward
  service: name=confluence state=stopped
  when: confluence_lcm['operation'] in ['upgrade','rollback','rollforward']
  notify:
    - confluence-systemctl-daemon-reload
    - confluence-systemctl-restart

- include_tasks: database.yml
  when: confluence_database_inventory_hostname is defined and confluence_database_type == 'postgresql'

- include: install.yml
- include: cert.yml
- include: jmx.yml

- name: Import CA bundles
  include_role:
    name: c2platform.core.java
    tasks_from: main
  vars:
    java_version: confluence
    java_versions:
      confluence:
        java_home: "{{ confluence_home_version_app }}/jre"
        bundles: "{{ confluence_ca_bundles }}"
        notify: confluence-systemctl-restart
        install: false # we are only managing keystore
  when: confluence_ca_bundles is defined

- name: Import trusted certificates
  include_role:
    name: c2platform.core.java
    tasks_from: main
  vars:
    java_version: confluence
    java_versions:
      confluence:
        java_home: "{{ confluence_home_version_app }}/jre"
        keystore: "{{ confluence_home_version_app }}/jre/lib/security/cacerts"
    java_trusted_sites_enabled: yes
    java_trusted_sites:
      certs: "{{ confluence_trusted_sites }}"
      notify: confluence-systemctl-restart
  when: confluence_trusted_sites is defined

- include: service.yml
